#!/usr/bin/env bash
# Script that configures a new Ubuntu machine
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
sudo echo "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 221221-web-01 54.160.123.84:80 check\n\tserver 221221-web-01 34.232.70.79:80 check" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
