#!/usr/bin/env bash
# Script that configures a new Ubuntu machine
config="\

global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    mode http
    balance roundrobin
    server 221221-web-01 54.82.210.126:80 check
    server 221221-web-02 18.233.67.22:80 check                               
"

# Update packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$config" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart